version: '3'

services:
  mariadb:
    container_name: ngukurban_db
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080